I-Volunteer-Manas-maps/I_Volenteer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('NLP.urls')),
    path('admin/', admin.site.urls),
]

I-Volunteer-Manas-maps/NLP/urls.py
from django.urls import path

from . import views, text2info

app_name = 'NLP'
urlpatterns = [
    path('', views.home, name='home'),
    path('maps/',views.maps,name='maps'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('test/',views.index,name='index'),
    path('upload',views.upload,name='upload'),
]

I-Volunteer-Manas-maps/NLP/models.py
from django.db import models

# Create your models here.

class NLP_MAPS(models.Model):
    id = models.IntegerField(primary_key=True)
    x = models.FloatField() 
    y = models.FloatField()
    Address = models.TextField()
    intensity = models.IntegerField()
    Remarks = models.CharField(max_length=50,default='Road Block',)

    def __str__(self):
        return self.Address 

I-Volunteer-Manas-maps/NLP/views.py
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage

from NLP.models import NLP_MAPS
from NLP.audio2text import *
from NLP.text2info import *
# Create your views here.
import googlemaps
from . import text2info

from .models import NLP_MAPS

def index(location):
    template = 'NLP/index.html'
    map = NLP_MAPS()
    res = {}
    res['Address'] = locations
    res['Intensity']=1
    #res = text2info.get_info()
    print("here ", res)
    gmaps = googlemaps.Client(key='AIzaSyBdl9Xvi8Yipfx-ldaB9RtluwGEyuU1KHM')
    print("kiops")
    geocode_result = gmaps.geocode(res['Address'])
    print("asaasa")
    print(geocode_result)
    # print(geocode_result)
    map.Address = res['Address']
    map.x = geocode_result[0]['geometry']['location']['lat']
    map.y = geocode_result[0]['geometry']['location']['lng']
    map.intensity = res['Intensity']
    map.save()
    #return render(request,template,{'res':res})

def dashboard(request):
    address = NLP_MAPS.objects.all()
    return render(request,'dashboard.html',{'address': address})

def home(request):
    return render(request,'Home/home.html')

def maps(request):
    address = NLP_MAPS.objects.values('id','x','y','Address')
    # serial = serializers.serialize('json', [ address, ])
    json_data = json.dumps(list(address))
    return render(request,'NLP/maps.html',{'address':json_data})

def upload(request):
    if request.method == 'GET' :
        return render(request,'NLP/upload.html')

    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        converted_text= get_text_from_audio(uploaded_file_url)
        #print(converted_text)
        info= get_info(converted_text['DisplayText'])
        #print(info)
        #Passing function to google map api
        #index(info[][])
        return render(request, 'NLP/upload.html', {
            'converted_text':converted_text,
            'info': info,
            })

I-Volunteer-Manas-maps/NLP/templates/Home/home.html
<!doctype html>
<html lang="en">
  <head>
    <title>I_volunteer</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Sacramento" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static "NLP/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/owl.carousel.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/ionicons/css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "NLP/fonts/fontawesome/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/flaticon/font/flaticon.css" %} ">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static "NLP/css/style.css" %} ">
  </head>
  <body>

    <header role="banner">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'NLP:home' %}">I_Volunteer</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'NLP:home' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://www.nsdma.gov.in/" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Donate</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href="https://www.karnatakaone.gov.in/">Karanatka Relief</a>
                  <a class="dropdown-item" href="http://www.nsdma.gov.in/">Nagaland Relief</a>
                  <a class="dropdown-item" href="https://donation.cmdrf.kerala.gov.in/">Kerel Relief</a>
                </div>

              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'NLP:dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'NLP:maps' %}">Maps</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'NLP:index' %}">Contact</a>
              </li>
            </ul>

          </div>
        </div>
      </nav>
    </header>
    <!-- END header -->

    <section class="home-slider inner-page owl-carousel">
      <div class="slider-item " style="background-image: url({% static 'NLP/img/slider-1.jpg' %});">

        <div class="container">
          <div class="row slider-text align-items-center">
            <div class="col-md-7 col-sm-12 element-animate">
              <h1>I_Volunteer</h1>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-custom">
                  <li class="breadcrumb-item"><a href="{% url 'NLP:dashboard' %}">Dashboard</a></li>
                  <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'NLP:maps' %}" >Maps</a></li>
                </ol>
              </nav>
            </div>
          </div>
        </div>

      </div>
    </section>
    <!-- END slider -->



    <section class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-8 order-1 main mb-5">
            <div class="row">

              <div class="col-md-12">
                <h2>Disaster Management </h2>
                <p>Disaster Management can be defined as the organization and management of resources and
                    responsibilities for dealing with all humanitarian aspects of emergencies,
                    in particular preparedness, response and recovery in order to lessen the impact of disasters.
                </p>
                <blockquote class="blockquote">
                  <p class="mb-0 text-black">
                        We cannot stop natural disasters but we can arm ourselves with knowledge:
                        so many lives wouldn't have to be lost if there was enough disaster preparedness.
                  </p>
                </blockquote>
              </div>
            </div>
          </div>

        </div>
        <!-- END row -->
      </div>
    </section>
    <footer class="site-footer" role="contentinfo">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-3 mb-5">
            <h3>About</h3>
            <p>Effort to crete a change in society for helping others</p>
            <p><a href="#">Learn More</a></p>
          </div>
          <div class="col-md-3">
            <h3>Contact &amp; Address</h3>
            <ul class="list-unstyled footer-link">
              <li class="d-flex"><span class="mr-3">A:</span><span class="text-white">NITK Hostels,NITK</span></li>
              <li class="d-flex"><span class="mr-3">T:</span><span class="text-white">+91 9404239451</span></li>
              <li class="d-flex"><span class="mr-3">E:</span><span class="text-white">contact@ivolunteer.nitk.edu.in</span></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 text-md-center text-left">

            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            <p>This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">I_Volunteer Team</a></p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </div>
        </div>
      </div>
    </footer>
    <!-- END footer -->

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'NLP/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'NLP/js/popper.min.js' %}"></script>
    <script src="{% static 'NLP/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'NLP/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'NLP/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'NLP/js/main.js' %}"></script>
  </body>
</html>

I-Volunteer-Manas-maps/NLP/templates/NLP/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="floating-panel">
        <div id="address" >{{ res }}</div>
      </div>
      <div id="map"></div>
</body>
</html>

I-Volunteer-Manas-maps/NLP/templates/NLP/maps.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Display markers</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Sacramento" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static "NLP/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/owl.carousel.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/ionicons/css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "NLP/fonts/fontawesome/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/flaticon/font/flaticon.css" %} ">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static "NLP/css/style.css" %} ">
</head>
    <style>
        #map {
          height: 100%;
        }
        html, body {
          height: 100%;
          margin: 0;
          padding: 0;
        }
    </style>
<body>
    <header role="banner">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
            <a class="navbar-brand" href="{% url 'NLP:home' %}">I_Volunteer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://www.nsdma.gov.in/" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Donate</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <a class="dropdown-item" href="https://www.karnatakaone.gov.in/">Karanatka Relief</a>
                    <a class="dropdown-item" href="http://www.nsdma.gov.in/">Nagaland Relief</a>
                    <a class="dropdown-item" href="https://donation.cmdrf.kerala.gov.in/">Kerel Relief</a>
                    </div>
    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'NLP:maps' %}">Maps</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:index' %}">Contact</a>
                </li>
                </ul>
                
            </div>
            </div>
        </nav>
    </header>
    <div id="map" class="container"></div>
    <script>
            function initMap() {
                var myLatLng = {lat: -25.363, lng: 131.044};
                var marker = new google.maps.Marker({
                  position: myLatLng,
                  map: map,
                  title: 'Hello World!'
                });
             var locations = {{address|safe}};
             var marker, i;
            console.log(locations)
             var map = new google.maps.Map(document.getElementById('map'), {
             zoom: 10,
             center: myLatLng
             });
             for (i = 0; i < locations.length; i++) { 
                 marker = new google.maps.Marker({

                     position: new google.maps.LatLng(locations[i]['x'], locations[i]['y']),
                     map: map,
                     title: locations[i]['Address']
                 });
            }
        }
    </script>
    <footer class="site-footer" role="contentinfo">
        <div class="container">
            <div class="row mb-5">
            <div class="col-md-3 mb-5">
                <h3>About</h3>
                <p>Effort to crete a change in society for helping others</p>
                <p><a href="#">Learn More</a></p>
            </div>
            <div class="col-md-3">
                <h3>Contact &amp; Address</h3>
                <ul class="list-unstyled footer-link">
                <li class="d-flex"><span class="mr-3">A:</span><span class="text-white">NITK Hostels,NITK</span></li>
                <li class="d-flex"><span class="mr-3">T:</span><span class="text-white">+91 9404239451</span></li>
                <li class="d-flex"><span class="mr-3">E:</span><span class="text-white">contact@ivolunteer.nitk.edu.in</span></li>
                </ul>
            </div>
            </div>
            <div class="row">
            <div class="col-12 text-md-center text-left">
    
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <p>This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">I_Volunteer Team</a></p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </div>
            </div>
        </div>
    </footer>
        <!-- END footer -->
    
        <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'NLP/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'NLP/js/popper.min.js' %}"></script>
    <script src="{% static 'NLP/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'NLP/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'NLP/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'NLP/js/main.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIwjk_H3Sp4yi8sxl2UOPwS-v7iULy7C4&callback=initMap">
    </script>
</body>
</html>

I-Volunteer-Manas-maps/NLP/templates/NLP/upload.html
<!DOCTYPE html>


{% block content %}
  <form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
  <p> The file must be a wav file with sampling rate of 16kHz and 16 bit PCM mono file </p>

  {% if converted_text %}
    <p>Text obtained from audio is: <a href="#">{{converted_text}}</a></p>
  {% endif %}

  {% if info %}
    <p>Information extracted is: <a href="#">{{info}}</a></p>
  {% endif %}

  <p><a href="#">Return to home</a></p>
{% endblock %}

I-Volunteer-Manas-maps/NLP/templates/dashboard.html
<!doctype html>
<html lang="en">
<head>
        <title>I_volunteer</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Sacramento" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static "NLP/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/owl.carousel.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/ionicons/css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "NLP/fonts/fontawesome/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/flaticon/font/flaticon.css" %} ">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static "NLP/css/style.css" %} ">
    <style>
            h1{
                font-size: 30px;
                color: #fff;
                text-transform: uppercase;
                font-weight: 300;
                text-align: center;
                margin-bottom: 15px;
              }
              table{
                width:100%;
                table-layout: fixed;
              }
              .tbl-header{
                background-color: rgba(255,255,255,0.3);
               }
              .tbl-content{
                height:300px;
                overflow-x:auto;
                margin-top: 0px;
                border: 1px solid rgba(255,255,255,0.3);
              }
              th{
                padding: 20px 15px;
                text-align: left;
                font-weight: 500;
                font-size: 12px;
                color: #fff;
                text-transform: uppercase;
              }
              td{
                padding: 15px;
                text-align: left;
                vertical-align:middle;
                font-weight: 300;
                font-size: 12px;
                color: #fff;
                border-bottom: solid 1px rgba(255,255,255,0.1);
              }
              
              
              
              @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
              body{
                background: -webkit-linear-gradient(left, #25c481, #25b7c4);
                background: linear-gradient(to right, #25c481, #25b7c4);
                font-family: 'Roboto', sans-serif;
              }
              section{
                margin: 50px;
              }
              .made-with-love {
                margin-top: 40px;
                padding: 10px;
                clear: left;
                text-align: center;
                font-size: 10px;
                font-family: arial;
                color: #fff;
              }
              .made-with-love i {
                font-style: normal;
                color: #F50057;
                font-size: 14px;
                position: relative;
                top: 2px;
              }
              .made-with-love a {
                color: #fff;
                text-decoration: none;
              }
              .made-with-love a:hover {
                text-decoration: underline;
              }
              
              ::-webkit-scrollbar {
                  width: 6px;
              } 
              ::-webkit-scrollbar-track {
                  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
              } 
              ::-webkit-scrollbar-thumb {
                  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
              }
    </style>
</head>
<body>
    <header role="banner">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
            <a class="navbar-brand" href="{% url 'NLP:home' %}">I_Volunteer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="https://www.karnatakaone.gov.in/Info/Public/CalamityReliefFund" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Donate</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <a class="dropdown-item" href="https://www.karnatakaone.gov.in/Info/Public/CalamityReliefFund">Karanatka Relief</a>
                    <a class="dropdown-item" href="http://www.nsdma.gov.in/">Nagaland Relief</a>
                    <a class="dropdown-item" href="https://donation.cmdrf.kerala.gov.in/">Kerel Relief</a>
                    </div>
    
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'NLP:maps' %}">Maps</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:index' %}">Contact</a>
                </li>
                </ul>
                
            </div>
            </div>
        </nav>
    </header>
    <section>
            <!--for demo wrap-->
        <h1>Dashboard of Complaints</h1>
        <div class="tbl-header">
            <table cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr class="tbl-header">
                        <th>ID</th>
                        <th>Address</th>
                        <th>latitute</th>
                        <th>longitute</th>
                        <th>Remarks</th>
                    </tr>
                </thead>
            <tbody  class="tbl-content">
                {% for add in address %}
                    <tr>
                        <th>{{add.id}}</th>
                        <th>{{add.Address}}</th>
                        <th>{{add.x}}</th>
                        <th>{{add.y}}</th>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </section>
    <script>
            $(window).on("load resize ", function() {
                var scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
                $('.tbl-header').css({'padding-right':scrollWidth});
              }).resize();
    </script>
    <footer class="site-footer" role="contentinfo">
            <div class="container">
              <div class="row mb-5">
                <div class="col-md-3 mb-5">
                  <h3>About</h3>
                  <p>Effort to crete a change in society for helping others</p>
                  <p><a href="#">Learn More</a></p>
                </div>
                <div class="col-md-3">
                  <h3>Contact &amp; Address</h3>
                  <ul class="list-unstyled footer-link">
                    <li class="d-flex"><span class="mr-3">A:</span><span class="text-white">NITK Hostels,NITK</span></li>
                    <li class="d-flex"><span class="mr-3">T:</span><span class="text-white">+91 9404239451</span></li>
                    <li class="d-flex"><span class="mr-3">E:</span><span class="text-white">contact@ivolunteer.nitk.edu.in</span></li>
                  </ul>
                </div>
              </div>
              <div class="row">
                <div class="col-12 text-md-center text-left">
      
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  <p>This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">I_Volunteer Team</a></p>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
              </div>
            </div>
          </footer>
          <!-- END footer -->
      
          <!-- loader -->
          <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>      
    <script src="{% static 'NLP/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'NLP/js/popper.min.js' %}"></script>
    <script src="{% static 'NLP/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'NLP/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'NLP/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'NLP/js/main.js' %}"></script>
</body>
</html>